<?php require('header.phtml'); ?>

<!-- Form container !-->
<div class="container-fluid" id="students-form-container">
    <div class="col-md-12" id="students-heading-container">
        <h3>Add new student</h3>
    </div>
    <div class="col-md-10 col-md-offset-3 column">
        <form id="student-form" class="form-horizontal" method="post">
            <input type="hidden" name="csrf_field" value="csrf">
            <div class="form-group">
                <label for="students-first-name-field" class="col-sm-2 control-label">First name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control"
                     name="firstName" id="students-first-name-field"
                     pattern="^[А-ЯЁA-Z][-а-яёa-zА-ЯЁA-Z\s]{1,15}$"
                     title="First name must begin with a capital letter, it must be shorter than 15 symblos, first name can consist of latin, cyrillc symbols, apostrophes, hyphens and spaces."
                     placeholder="First name" required>
                </div>
            </div>
            <div class="form-group">
                <label for="students-last-name-field" class="col-sm-2 control-label">Last name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control"
                     name="lastName" id="students-last-name-field"
                     pattern="^[А-ЯЁA-Z][-'`а-яёa-zА-ЯЁA-Z\s]{1,20}$"
                     title="Last name must begin with a capital letter, it must be shorter than 20 symblos, last name can consist of latin, cyrillc symbols, apostrophes, hyphens and spaces."
                     placeholder="Last name" required>
                </div>
            </div>
            <div class="form-group">
                <label for="students-gender-radio" class="col-sm-2 control-label">Gender</label>
                <div class="radio col-sm-4 students-gender-selection" id="students-gender-radio">
                    <label>
                        <input type="radio" name="gender" value="male" checked>
                        Male
                    </label>
                    <label>
                        <input type="radio" name="gender" value="female">
                        Female
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label for="group" class="col-sm-2 control-label">Group name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control"
                     name="group" id="group"
                     pattern="^[-А-ЯЁа-яёa-zA-Z0-9]{2,5}$"
                     title="Group name must be longer than 2 and not longer than 5 symbols, group name can consist of latin, cyrillic symols, numbers and hyphens."
                     placeholder="Group name" required>
                </div>
            </div>
            <div class="form-group">
                <label for="students-email-field" class="col-sm-2 control-label">E-mail</label>
                <div class="col-sm-4">
                    <input type="email" class="form-control"
                     name="email" id="students-email-field"
                     title="E-mail must be in name@example.com format."
                     placeholder="E-mail" required>
                </div>
            </div>
            <div class="form-group">
                <label for="students-birth-year-field" class="col-sm-2 control-label">Birth year</label>
                <div class="col-sm-4">
                    <input type="number" class="form-control"
                     name="birthYear" id="students-birth-year-field"
                     min="1900" max="2000"
                     title="Birth year must be bigger than 1900 and not bigger than 2000."
                     placeholder="Birth year" required>
                </div>
            </div>
            <div class="form-group">
                <label for="students-status-radio" class="col-sm-2 control-label">Status</label>
                <div class="radio col-sm-4 students-gender-selection" id="students-status-radio">
                    <label>
                        <input type="radio" name="status" value="nonresident" checked>
                        Non-resident
                    </label>
                    <label>
                        <input type="radio" name="status" value="resident">
                        Resident
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label for="students-rating-field" class="col-sm-2 control-label">Rating</label>
                <div class="col-sm-4">
                    <input type="number" class="form-control"
                     name="rating" id="students-rating-field"
                     min="0" max="300"
                     title="Rating must be bigger than 0 and not bigger than 300."
                     placeholder="Student rating" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2">
                    <button type="submit" class="btn btn-default">Send</button>
                </div>
            </div>
        </form>
    </div>
</div><!-- /.container-fluid -->

<?php require('footer.phtml'); ?>