<?php require('header.phtml'); ?>

<!-- Errors container !-->
<div class="container-fuluid">
    <?php foreach($errors as $name => $text): ?>
        <?php if(in_array($name, ['gender', 'status'])): ?>
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                <?= $text ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>

<!-- Form container !-->
<div class="container-fluid" id="students-form-container">
    <div class="col-md-12" id="students-heading-container">
        <h3>
            <?php if($authorized !== true): ?>
                Add new student
            <?php else: ?>
                Edit existing student
            <?php endif; ?>
        </h3>
    </div>
    <div class="col-md-10 col-md-offset-3 column">
        <form id="student-form" class="form-horizontal" method="post">
            <input type="hidden" name="csrf" value="<?= $csrfToken ?>">
            <div class="form-group <?php if(isset($errors['firstName'])): ?>has-error<?php endif; ?>">
                <label for="students-first-name-field" class="col-sm-2 control-label">First name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control"
                     name="firstName" id="students-first-name-field"
                     pattern="^[А-ЯЁA-Z][-а-яёa-zА-ЯЁA-Z\s]{1,15}$"
                     value="<?= $student->getFirstName() ?>"
                     title="First name must begin with a capital letter, it must be shorter than 15 symblos, first name can consist of latin, cyrillc symbols, apostrophes, hyphens and spaces."
                     placeholder="First name" required>
                     <?php if(isset($errors['firstName'])): ?>
                         <span class="help-block">
                             <?= $errors['firstName'] ?>
                         </span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="form-group <?php if(isset($errors['lastName'])): ?>has-error<?php endif; ?>">
                <label for="students-last-name-field" class="col-sm-2 control-label">Last name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control"
                     name="lastName" id="students-last-name-field"
                     pattern="^[А-ЯЁA-Z][-'`а-яёa-zА-ЯЁA-Z\s]{1,20}$"
                     value="<?= $student->getLastName() ?>"
                     title="Last name must begin with a capital letter, it must be shorter than 20 symblos, last name can consist of latin, cyrillc symbols, apostrophes, hyphens and spaces."
                     placeholder="Last name" required>
                     <?php if(isset($errors['lastName'])): ?>
                         <span class="help-block">
                             <?= $errors['lastName'] ?>
                         </span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="form-group">
                <label for="students-gender-radio" class="col-sm-2 control-label">Gender</label>
                <div class="radio col-sm-4 students-gender-selection" id="students-gender-radio">
                    <label>
                        <input type="radio" name="gender" value="male"
                            <?php if($student->getGender() != 'female'): ?>checked<?php endif; ?>>
                        Male
                    </label>
                    <label>
                        <input type="radio" name="gender" value="female"
                            <?php if($student->getGender() == 'female'): ?>checked<?php endif; ?>>
                        Female
                    </label>
                </div>
            </div>
            <div class="form-group <?php if(isset($errors['group'])): ?>has-error<?php endif; ?>">
                <label for="group" class="col-sm-2 control-label">Group name</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control"
                     name="group" id="group"
                     pattern="^[-А-ЯЁа-яёa-zA-Z0-9]{2,5}$"
                     value="<?= $student->getGroup() ?>"
                     title="Group name must be longer than 2 and not longer than 5 symbols, group name can consist of latin, cyrillic symols, numbers and hyphens."
                     placeholder="Group name" required>
                     <?php if(isset($errors['group'])): ?>
                         <span class="help-block">
                             <?= $errors['group'] ?>
                         </span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="form-group <?php if(isset($errors['email'])): ?>has-error<?php endif; ?>">
                <label for="students-email-field" class="col-sm-2 control-label">E-mail</label>
                <div class="col-sm-4">
                    <input type="email" class="form-control"
                     name="email" id="students-email-field"
                     value="<?= $student->getEmail() ?>"
                     title="E-mail must be in name@example.com format."
                     placeholder="E-mail" required>
                     <?php if(isset($errors['email'])): ?>
                         <span class="help-block">
                             <?= $errors['email'] ?>
                         </span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="form-group <?php if(isset($errors['birthYear'])): ?>has-error<?php endif; ?>">
                <label for="students-birth-year-field" class="col-sm-2 control-label">Birth year</label>
                <div class="col-sm-4">
                    <input type="number" class="form-control"
                     name="birthYear" id="students-birth-year-field"
                     min="1900" max="2000"
                     value="<?= $student->getBirthYear() ?>"
                     title="Birth year must be bigger than 1900 and not bigger than 2000."
                     placeholder="Birth year" required>
                     <?php if(isset($errors['birthYear'])): ?>
                         <span class="help-block">
                             <?= $errors['birthYear'] ?>
                         </span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="form-group">
                <label for="students-status-radio" class="col-sm-2 control-label">Status</label>
                <div class="radio col-sm-4 students-gender-selection" id="students-status-radio">
                    <label>
                        <input type="radio" name="status" value="nonresident"
                            <?php if($student->getStatus() != 'resident'): ?>checked<?php endif; ?>>
                        Non-resident
                    </label>
                    <label>
                        <input type="radio" name="status" value="resident"
                            <?php if($student->getStatus() == 'resident'): ?>checked<?php endif; ?>>
                        Resident
                    </label>
                </div>
            </div>
            <div class="form-group <?php if(isset($errors['rating'])): ?>has-error<?php endif; ?>">
                <label for="students-rating-field" class="col-sm-2 control-label">Rating</label>
                <div class="col-sm-4">
                    <input type="number" class="form-control"
                     name="rating" id="students-rating-field"
                     min="0" max="300"
                     value="<?= $student->getRating() ?>"
                     title="Rating must be bigger than 0 and not bigger than 300."
                     placeholder="Student rating" required>
                     <?php if(isset($errors['rating'])): ?>
                         <span class="help-block">
                             <?= $errors['rating'] ?>
                         </span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2">
                    <button type="submit" class="btn btn-default">Send</button>
                </div>
            </div>
        </form>
    </div>
</div><!-- /.container-fluid -->

<?php require('footer.phtml'); ?>