<?php require('header.phtml'); ?>

<?php if(!isset($students) && empty($students)): ?>
    Student list is empty.
<?php else: ?>
    <div class="container-fluid">
        <!-- Search box !-->
        <div class="col-md-6 col-md-offset-3" id="students-search-container">
            <form method="get">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Search for..." required>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Search</button>
                    </span>
                </div><!-- /input-group -->
            </form>
        </div><!-- /.col-md-4 -->
        <!-- Student list !-->
        <div class="panel panel-default col-md-12 students-list-table-container">
            <table class="table students-list-table">
                <!-- Student list row names !-->
                <tr class="students-list-table-header">
                    <th><a href="<?= $linker->toSorting('id') ?>">#</a></th>
                    <th><a href="<?= $linker->toSorting('name') ?>">First name</a></th>
                    <th><a href="<?= $linker->toSorting('surname') ?>">Last name</a></th>
                    <th><a href="<?= $linker->toSorting('sgroup') ?>">Group</a></th>
                    <th><a href="<?= $linker->toSorting('rating') ?>">Rating</a></th>
                </tr>
                <?php foreach($students as $key => $student): ?>
                    <tr>
                        <td><?= htmlspecialchars($student->getId()) ?></td>
                        <td><?= htmlspecialchars($student->getFirstName()) ?></td>
                        <td><?= htmlspecialchars($student->getLastName()) ?></td>
                        <td><?= htmlspecialchars($student->getGroup()) ?></td>
                        <td><?= htmlspecialchars($student->getRating()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </table><!-- /.table -->
        </div>
    </div><!-- /.container-fluid -->
    <?php if($pager->getPages() > 1): ?>
        <nav aria-label="Page navigation" id="students-navigation-container">
            <ul class="pagination pagination-lg">
                <li <?php if($page <= 1): ?> class="disabled" <?php endif; ?> >
                    <a <?php if($page > 1): ?> href="<?= $linker->toPage($page - 1) ?>" aria-label="Previous" <?php endif; ?> >
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <!-- Page nubmers start !-->
                <?php $starterPage = ($page > 1) ? $page - 1 : $page; ?>
                <?php $pagesTotal = ($page + 2) <= $pager->getPages() ? $page + 2 : $page + ($pager->getPages() - $page) ?>
                <?php for($i = $starterPage; $i <= $pagesTotal; $i++): ?>
                    <li "<?php if($i == $page): ?> class='active' <?php endif; ?>">
                        <a <?php if($i !== $page): ?> href="<?= $linker->toPage($i) ?>" <?php endif; ?> >
                            <?= $i ?>
                        </a>
                    </li>
                <?php endfor; ?>
                <!-- Page nubmers end !-->
                <li <?php if($page >= $pager->getPages()): ?> class="disabled" <?php endif; ?> >
                    <a <?php if($page < $pager->getPages()): ?> href="<?= $linker->toPage($page + 1) ?>" aria-label="Next" <?php endif; ?>>
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    <?php endif; ?>
<?php endif; ?>

<?php require('footer.phtml'); ?>