<?php require('header.phtml'); ?>

<?php if(empty($students) && empty($searchQuery)): ?>
    <div class="alert alert-info" role="alert">
        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
        Student list is currently empty. You can start by adding your info to the list
        <a href="/form" class="alert-link"> on the registration page.</a>
    </div>
<?php else: ?>
    <div class="container-fluid">
        <?php if(isset($notification)): ?>
            <div class="alert alert-success" role="alert">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                Your information was successfully <?= $notification ?>.
            </div>
        <?php endif; ?>
        <!-- Search box !-->
        <div class="container-fluid">
            <div class="col-md-12" id="students-search-container">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="search" class="form-control"
                        value="<?= $searchQuery ?>" placeholder="Search for..." required>
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Search</button>
                        </span>
                    </div><!-- /input-group -->
                </form>
            </div><!-- /.col-md-12 -->
        </div>

        <?php if(!empty($searchQuery)): ?>
            <!-- Search notifications !-->
            <div class="alert alert-<?php if(empty($students)): ?>warning<?php else: ?>info<?php endif; ?>"
                role="alert">
                <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                <?php if(empty($students)): ?>
                    No students found by &laquo;<i><?= htmlspecialchars($searchQuery) ?></i>&raquo; search query.
                    Check your search query for typos or <a href="/" class="alert-link">return to the main page.</a>
                <?php else: ?>
                    Currently displaying students that were found by &laquo;<i><?= htmlspecialchars($searchQuery) ?></i>&raquo;
                    search query. <a href="/" class="alert-link">Return to the main page</a> to view the whole list.
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <!-- Student list !-->
        <div class="panel panel-default col-md-12 students-list-table-container">
            <table class="table students-list-table">
                <!-- Student list row names !-->
                <tr class="students-list-table-header">
                    <th><a href="<?= $linker->toSorting('id') ?>">#</a></th>
                    <th><a href="<?= $linker->toSorting('name') ?>">First name</a></th>
                    <th><a href="<?= $linker->toSorting('surname') ?>">Last name</a></th>
                    <th><a href="<?= $linker->toSorting('sgroup') ?>">Group</a></th>
                    <th><a href="<?= $linker->toSorting('rating') ?>">Rating</a></th>
                </tr>
                <!-- Student list row values !-->
                <?php foreach($students as $key => $listStudent): ?>
                    <tr>
                        <td><?= htmlspecialchars($listStudent->getId()) ?></td>
                        <td><?= htmlspecialchars($listStudent->getFirstName()) ?></td>
                        <td><?= htmlspecialchars($listStudent->getLastName()) ?></td>
                        <td><?= htmlspecialchars($listStudent->getGroup()) ?></td>
                        <td><?= htmlspecialchars($listStudent->getRating()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </table><!-- /.table -->
        </div>
    </div><!-- /.container-fluid -->
    <?php if($pager->getPages() > 1): ?>
        <nav aria-label="Page navigation" id="students-navigation-container">
            <ul class="pagination pagination-lg">
                <li <?php if($page <= 1): ?> class="disabled" <?php endif; ?> >
                    <a <?php if($page > 1): ?> href="<?= $linker->toPage($page - 1) ?>" aria-label="Previous" <?php endif; ?> >
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <!-- Page nubmers start !-->
                <?php $starterPage = ($page > 1) ? $page - 1 : $page; ?>
                <?php $pagesTotal = ($page + 2) <= $pager->getPages() ? $page + 2 : $page + ($pager->getPages() - $page) ?>
                <?php for($i = $starterPage; $i <= $pagesTotal; $i++): ?>
                    <li "<?php if($i == $page): ?> class='active' <?php endif; ?>">
                        <a <?php if($i !== $page): ?> href="<?= $linker->toPage($i) ?>" <?php endif; ?> >
                            <?= $i ?>
                        </a>
                    </li>
                <?php endfor; ?>
                <!-- Page nubmers end !-->
                <li <?php if($page >= $pager->getPages()): ?> class="disabled" <?php endif; ?> >
                    <a <?php if($page < $pager->getPages()): ?> href="<?= $linker->toPage($page + 1) ?>" aria-label="Next" <?php endif; ?>>
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    <?php endif; ?>
<?php endif; ?>

<?php require('footer.phtml'); ?>