<?php
    $pageTitle = "Главная страница";
    $navTitle = "index";
?>
<?php include("header.phtml") ?>
<div id="content">

    <?php if($success): ?>
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon glyphicon-ok" aria-hidden="true"></span>
            Информация успешно добавлена в базу данных.
        </div>
    <?php endif; ?>

    <?php if($students || $tableHelper->searchPattern != null): ?>
        <form method="get">
            <div class="row" id="search_box">
                <div class="col-lg-4 col-lg-offset-4">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Поиск</button>
                        </span>
                        <input type="text" name="search" class="form-control"
                        placeholder="Введите запрос для поиска"
                        value="<?= htmlspecialchars($tableHelper->searchPattern) ?>" required>
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
            </div>
        </form>
    <?php endif; ?>

    <?php if($students): ?>
        <?php if($tableHelper->searchPattern != null): ?>
            <p class="search-info">Показаны результаты по запросу &laquo;<?= htmlspecialchars($tableHelper->searchPattern) ?>&raquo;</p>
            <p class="search-info" id="text-all"><a href="index.php">Показать все записи</a></p>
        <?php endif; ?>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">Список студентов</div>
            <table class="table">
                <tr>
                    <?php foreach($tableHelper->getTableHeaders() as $key => $name): ?>
                        <th>
                            <a href="<?= htmlspecialchars($tableHelper->getSortingLink($key)) ?>"><?= $name ?></a>
                            <?php if($tableHelper->sortKey == $key): ?>
                                <span class="glyphicon <?= $tableHelper->getSortingGlyphicon() ?>" aria-hidden="true"></span>
                            <?php endif; ?>
                        </th>
                    <?php endforeach; ?>
                </tr>
                <?php foreach($students as $student): ?>
                    <tr>
                        <td><?= htmlspecialchars($student->getName()) ?></td>
                        <td><?= htmlspecialchars($student->getSurname()) ?></td>
                        <td><?= htmlspecialchars($student->getGroup()) ?></td>
                        <td><?= htmlspecialchars($student->getRating()) ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <?php if($pager->getPages() > 1): ?>
            <nav id="table_nav">
                <ul class="pagination pagination-lg">
                    <li <?php if($currentPage <= 1): ?> class="disabled" <?php endif; ?> >
                        <a <?php if($currentPage > 1): ?> href="<?= $tableHelper->getPageLink($currentPage - 1) ?>" aria-label="Previous" <?php endif; ?> >
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <!-- Page nubmers start !-->
                    <?php $starterPage = ($currentPage > 1) ? $currentPage - 1 : $currentPage; ?>
                    <?php $pagesTotal = ($currentPage + 2) <= $pager->getPages() ? $currentPage + 2 : $currentPage + ($pager->getPages() - $currentPage) ?>
                    <?php for($i = $starterPage; $i <= $pagesTotal; $i++): ?>
                        <li "<?php if($i == $currentPage): ?> class='active' <?php endif; ?>">
                            <a <?php if($i !== $currentPage): ?> href="<?= $tableHelper->getPageLink($i) ?>" <?php endif; ?> >
                                <?= $i ?>
                            </a>
                        </li>
                    <?php endfor; ?>
                    <!-- Page nubmers end !-->
                    <li <?php if($currentPage >= $pager->getPages()): ?> class="disabled" <?php endif; ?> >
                        <a <?php if($currentPage < $pager->getPages()): ?> href="<?= $tableHelper->getPageLink($currentPage + 1) ?>" aria-label="Next" <?php endif; ?>>
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        <?php endif; ?>

    <?php else: ?>
        <h3 class="student-list-message">
            <?php if($tableHelper->searchPattern != null): ?>
                По запросу &laquo;<?= htmlspecialchars($tableHelper->searchPattern) ?>&raquo; не найдено ни одного студента.
            <?php else: ?>
                Список студентов пуст.
            <?php endif; ?>
        </h3>
    <?php endif; ?>
</div>
</body>
</html>